#!/bin/bash

# This is a thin wrapper around conbinicoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using conbinicoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_CONBINICOIND

# Grab the value of $REAL_CONBINICOINCLI which may be conbinicoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_CONBINICOINCLI}" "$@" | sed 's/\r//'
